name: investtrack_india
description: A privacy-focused investment tracking app for Indian users

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Database - Using stable versions
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Email
  url_launcher: ^6.1.7

  # File & Share
  path_provider: ^2.0.0
  share_plus: ^7.2.2      # upgraded to match win32 >=4.0.0 <6.0.0
  
  # Security & Authentication
  local_auth: ^2.1.8
  
  # Charts and Data Visualization
  fl_chart: ^0.68.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # App Info
  package_info_plus: ^5.0.1
  
  # Utilities
  intl: ^0.19.0              # For Indian currency formatting
  uuid: ^4.1.0               # For generating unique IDs
  
  # UI
  cupertino_icons: ^1.0.2    # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/icons/app_icon.png"  # path to your new icon
  ios: true
  android: true

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/icons/
    - assets/images/
    - assets/
